export const types = {
  SET_USER_DATA: "SET_USER_DATA",
  SET_USER_REPOSITORIES: "SET_USER_REPOSITORIES",
  SET_USERS_SEARCHED: "SET_USERS_SEARCHED",
  SET_USER_CONTENT: "SET_USER_CONTENT",
  SET_USER_REPOSITORY: "SET_USER_REPOSITORY",
  SET_DATA_FOR_NESTING: "SET_DATA_FOR_NESTING",
  SET_DATA_FOR_BRANCHES: "SET_DATA_FOR_BRANCHES",
  SET_DATA_FOR_PROFILE_BRANCHES: "SET_DATA_FOR_PROFILE_BRANCHES",
};
